[logger]
    name = ""                                                           # имя логгера
    levels = ["critical","log","error","warn","debug","verbose"]        # уровни логирования
    [logger.bindings]                                                   # дополнительные ключи
        key1 = "key1-val"
        key2 = "key2-val"
    [logger.output]                                                     # настройка отображения
        timestamp = "full"                                              # вывод времени full, short, unix и none
        levels = ["critical","log","error","warn","debug","verbose"]    # вывод типов
        bindings = "bracket"                                            # отображение ключей square, bracket, none

[api]                       # настройка API сервера
    enable = false          # активация
    hostname = "localhost"  # хост          
    port = 3001             # порт
    prefix = "/api"         # префикс
    [api.security]                  # настройка безопасности
        [api.security.helmet]       # настройка helmet (пакет https://github.com/helmetjs/helmet)
            enable = true           # активация helmet
        [api.security.rate_limit]   # настройка ограничений количества запроса
            enable = false          # активация ограничений
            ttl = 30                # временное окно
            limit = 10              # количество запросов
            ignore_agents = []      # массив регулярных выражений агентов для игнорирования правил
        [api.security.cors]                                         # настройка CORS (пакет https://github.com/expressjs/cors)
            enable = false                                          # активация cors
            origin = "*"                                            # допустимые домены
            methods = ["GET","HEAD","PUT","PATCH","POST","DELETE"]  # допустимые методы
            allowed_headers = []                                    # настройка Access-Control-Allow-Headers CORS заголовка
            exposed_headers = []                                    # настройка Access-Control-Expose-Headers CORS заголовка
            credentials = false                                     # настройка Access-Control-Allow-Credentials CORS заголовка
            preflight_continue = false                              # передавать ответ CORS следующему обработчику
            options_success_status = 204                            # код ответа для OPTIONS запроса
            max_age = 0                                             # настройка Access-Control-Max-Age CORS заголовка

[web]
    enable = false          # активация Web сервера
    hostname = "localhost"  # хост          
    port = 3000             # порт
    prefix = "/"            # префикс
    [web.static]                # настройка статического контента
        root_path = "static"    # root папка
        exclude = []            # игнорируемые пути в формате wildcard
        index_redirect = true   # выдать индекс при запросе "/"
        index = "index.html"    # index по умолчанию
    [web.security]                  # настройка безопасности
        [web.security.helmet]       # настройка helmet (пакет https://github.com/helmetjs/helmet)
            enable = true           # активация helmet
        [web.security.rate_limit]   # настройка ограничений количества запроса
            enable = false          # активация ограничений
            ttl = 30                # временное окно
            limit = 10              # количество запросов
            ignore_agents = []      # массив регулярных выражений агентов для игнорирования правил
        [web.security.cors]                                         # настройка CORS (пакет https://github.com/expressjs/cors)
            enable = false                                          # активация cors
            origin = "*"                                            # допустимые домены
            methods = ["GET","HEAD","PUT","PATCH","POST","DELETE"]  # допустимые методы
            allowed_headers = []                                    # настройка Access-Control-Allow-Headers CORS заголовка
            exposed_headers = []                                    # настройка Access-Control-Expose-Headers CORS заголовка
            credentials = false                                     # настройка Access-Control-Allow-Credentials CORS заголовка
            preflight_continue = false                              # передавать ответ CORS следующему обработчику
            options_success_status = 204                            # код ответа для OPTIONS запроса
            max_age = 0                                             # настройка Access-Control-Max-Age CORS заголовка