[logger]
    name = ""                                                           # имя логгера
    levels = ["critical","log","error","warn","debug","verbose"]        # уровни логирования
    [logger.bindings]                                                   # дополнительные ключи
        key1 = "key1-val"
        key2 = "key2-val"
    [logger.output]                                                     # настройка отображения
        timestamp = "full"                                              # вывод времени full, short, unix и none
        levels = ["critical","log","error","warn","debug","verbose"]    # вывод типов
        bindings = "bracket"                                            # отображение ключей square, bracket, none

[api]                       # настройка API сервера
    enable = false          # активация
    hostname = "localhost"  # хост          
    port = 3001             # порт
    prefix = "/api"         # префикс
    [api.security]
        [api.security.helmet]
            enable = true
        [api.security.rate_limit]
            enable = false
            ttl = 30
            limit = 10
            ignore_agents = []

[web]
    enable = false          # активация Web сервера
    hostname = "localhost"  # хост          
    port = 3000             # порт
    prefix = "/"            # префикс
    [web.static]                # настройка статического контента
        root_path = "static"    # root папка
        exclude = []            # игнорируемые пути в формате wildcard
        index_redirect = true   # выдать индекс при запросе "/"
        index = "index.html"    # index по умолчанию
    [web.security]
        [web.security.helmet]
            enable = true
        [web.security.rate_limit]
            enable = false
            ttl = 30
            limit = 10
            ignore_agents = []

    